### ISSUE TITLE
Is braid still being hacked on?

### ISSUE THREAD

**Issue by prologic** [joshsharp/braid#1]

**Comment by joshsharp** [comment]
Well, I haven't had time to work on it actively for a while now, but I'm still interested in building it out further at some stage.

**Comment by prologic** [comment]
I'm interested too probably for the same reasons you are :) I'm also
interested in your project in particular because it's not crazy big or
complex (yet!) and we seem to be mostly (more or less) at similar levels :)

One thing I'm struggling with at the moment is getting the right "Design
Pattern" for a REPL and changing the typical Stack Frame implementation for
an Execution Context. Does this make any sense? Most toy examples
(including kermit, hermit; which I've improved massively) just use a Stack
Frame so writing a REPL is hard :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by joshsharp** [comment]
You know, I should be honest, Braid in this iteration is probably dead. One thing I'm still interested in is emitting LLVM IR instead, probably from something I can compile more easily than RPython (maybe Rust or OCaml?). But good luck if you decide to hack on it! I'll be curious to see what you do with it.
